create table mpq_data.character_power ( 
    charcter_power_id integer primary key generated by default as identity, 
    character_id integer references mpq_data.mpq_character(mpq_charcter_id) not null, 
    ordinal_position integer not null, 
    color_id integer references mpq_data.color(color_id) not null,
    constraint ck_character_power_char_color unique (character_id, color_id), 
    constraint ck_character_power_position (ordinal_position between 1 and 3)
); 
