create table mpq_data.character_power ( 
    charcter_power_id integer primary key generated by default as identity, 
    character_id integer references mpq_data.mpq_character(mpq_charcter_id) not null, 
    ordinal_position integer not null, 
    name varchar(100) not null, 
    description varchar(5000) not null, 
    color_id integer references mpq_data.color(color_id) not null 
); 