-- drop table mpq_data.mpq_character ; 

create table mpq_data.mpq_character (
    mpq_charcter_id integer primary key generated by default as identity, 
    name varchar(250) not null, 
    style varchar(250) not null, 
    rarity integer not null, 
    release_date date 
); 

