create table mpq_data.power_mode ( 
    power_mode_id integer primary key generated by default as identity,
    charcter_power_id not null references mpq_data.character_power(charcter_power_id), 
    ordinal_position integer not null, 
    name varchar(100) not null, 
    description varchar(5000) not null, 
    constraint ck_character_power_char_color unique (character_id, color_id)
); 
