wiki:
    urls:
        - http://marvelpuzzlequest.wikia.com/wiki/Common
        - http://marvelpuzzlequest.wikia.com/wiki/Uncommon
        - http://marvelpuzzlequest.wikia.com/wiki/Rare
        - http://marvelpuzzlequest.wikia.com/wiki/Legendary
        - http://marvelpuzzlequest.wikia.com/wiki/Epic
